### ISSUE TITLE
[REFACTOR] MyTeam에 Tactic 적용 안해도 NULL값으로 나오게 적용

### ISSUE THREAD

**Issue by 600gramSik** [BangFer/BangFer-Back_End#65]
## 리팩토링 내용
- [ ] MyTeam에 Tactic 적용 안해도 NULL값으로 나오게 적용

**Comment by gomin0** [comment]
근식씨
GetTeamResponseDto 에서
![image](https://github.com/BangFer/BangFer-Back_End/assets/80516484/854db75a-ee8d-4299-b222-f5c393df9bd3)
이렇게 처리해 주니까
![image](https://github.com/BangFer/BangFer-Back_End/assets/80516484/fd90f0f8-0f86-443a-ae59-e7a324520f08)
null로 잘 나오네요..
참고..

**Comment by 600gramSik** [comment]
헉..... 형님.... 감사합니다......
